#!/usr/bin/env python
from setup_utils import *
import os

# ids.storage_hzb

actions, arg, props = getActions("setup.properties", [])


if arg in ["CONFIGURE", "INSTALL"]:
    actions.checkNoErrors()

if arg == "INSTALL":
    try:     
        app = actions.getAppName("ids.server")
        if app: actions.disableApp(app)   
        actions.removeFromApplibs("ids.storage_hzb*.jar")    
        actions.installToApplibs("ids.storage_hzb*.jar")
        actions.stopDomain()
        actions.startDomain()
        if app: actions.enableApp(app) 
    except Exception, e:
        raise
        abort(str(e))
                
if arg == "UNINSTALL":
    try:
        actions.removeFromApplibs("ids.storage_hzb*.jar")        
    except Exception, e:
        abort(str(e))       
    
            
    
